CREATE TABLE IF NOT EXISTS authors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR NOT NULL,
    second_name   VARCHAR NOT NULL,
    surname   VARCHAR NOT NULL,
    birth DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR NOT NULL,
    description   VARCHAR NOT NULL,
    author_id BIGINT NOT NULL REFERENCES authors (id) ON DELETE CASCADE ON UPDATE CASCADE,
    page_count INT NOT NULL,
    published INT NOT NULL
);

insert into authors values (1, 'Антон', 'Павлович', 'Чехов', '10.01.1890');
insert into authors values (2, 'Лев', 'Николаевич', 'Толстой', '10.01.1890');
insert into books values (1, 'Толстый и тонкий', 'Бла-бла', 1, 30, 1994);
insert into books values (2, 'Война и мир', 'Ту-ту', 2, 300, 1994);